//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parcial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int id_cliente { get; set; }
        public string no_cuenta { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string concepto_pago { get; set; }
        public decimal monto { get; set; }
    }
}
